datacollect2/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import IndexView, SaveShapefilesView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('save-shapefiles/', SaveShapefilesView.as_view(), name='save-shapefiles'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models


class Files(models.Model):
    user_id = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, default="Unnamed_GeoJSON")
    geojson = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user_id}- {self.name}"

main/forms.py
from django import forms

class ShapefileForm(forms.Form):
    zipfile = forms.FileField()

main/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import ShapefileForm
from .models import Files
from django.views.generic.base import TemplateView
from django.conf import settings
import os
from django.http import JsonResponse
from django.urls import reverse
from .shapefile_class import Shapefile as shp_op
from .helper_func import remove_files_in_folder, save_user_files, find_files, print_with_lines
import uuid
import time
import zipfile

class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def render(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)


    def get(self, request, **kwargs):
        user_id = request.COOKIES.get('user_id')

        print_with_lines(f"user_id: {user_id}")

        all_data = Files.objects.filter(user_id=user_id)
        geojson_list = []
        data_list = []
        for obj in all_data:
            data_dict = {
                'name': obj.name,
                'geojson': obj.geojson
            }
            data_list.append(data_dict)

        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse(data_list, safe=False)
        else:
            context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)


class SaveShapefilesView(View):
    template_name = 'main/upload_shapefile.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):

        print_with_lines(f"Post request received")
        form = ShapefileForm(request.POST, request.FILES)
        folder_path = os.path.join(settings.MEDIA_ROOT, 'shapefiles')

        print_with_lines(f"Form Initialized")

        time_start_check = time.time()
        if form.is_valid():
            user_id = request.COOKIES.get('user_id')
            if not user_id:
                success_msg = "deadserv: New User, post request was successful! Click on 'Load Layer' to add your data on the map. You can close this dailog box now."
                user_id = uuid.uuid4().hex
                
            else:
                success_msg = "deadserv: Returning user, post request was successful! Click on 'Load Layer' to add your data on the map. You can close this dailog box now."

            data = {'success_msg': success_msg}
            response = JsonResponse(data)
            response.set_cookie('user_id', user_id, max_age=3 * 24 * 60 * 60)
            time_end_check = time.time()

            print_with_lines(f"Form valid, user id checked, cookie set: {time_end_check - time_start_check}")
            
            user_folder_path = os.path.join(folder_path, user_id)
            if not os.path.exists(user_folder_path):
                os.mkdir(user_folder_path)
            
            remove_files_in_folder(user_folder_path)
            print_with_lines("Removed files in the user folder")

            zip_file = request.FILES['zipfile']
            print_with_lines(f"zip in request {zip_file}")

            zip_path = os.path.join(user_folder_path, zip_file.name)

            with open(zip_path, 'wb+') as destination:
                for chunk in zip_file.chunks():
                    destination.write(chunk)
            print_with_lines(f"Saved zip at: {zip_path}")

            time_start_save_to_storage = time.time()
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(user_folder_path)        
            time_end_save_to_storage = time.time()

            print_with_lines(f"Time taken to save the Compressed file in server storage: {time_end_save_to_storage - time_start_save_to_storage}")

            time_start_shp_process = time.time()
            shapefile_path = find_files(user_folder_path, "*", "shp")

            shp_operations = shp_op(shapefile_path)

            in_ds, in_layer, in_spatial_ref, in_geom = shp_operations.find_spatial_info(shapefile_path)

            time_start_transformation = time.time()
            shp_operations.srs_transformation(in_spatial_ref, 4326, in_geom, in_layer, user_folder_path)
            time_end_transformation = time.time()

            print_with_lines(f"Time taken to transformation: {time_end_transformation - time_start_transformation}")


            reprojected_shp_path = find_files(user_folder_path, "reprojected", "shp")

            print_with_lines("Converting shapefile to geojson")
            time_start_conversion = time.time()
            if reprojected_shp_path != None:
                geojson_str = shp_operations.shapefile_to_json(reprojected_shp_path)
            else:
                geojson_str = shp_operations.shapefile_to_json(shapefile_path)

            db_filename, extension = os.path.splitext(os.path.basename(shapefile_path)) # type: ignore
            time_end_shp_process = time.time()
            

            print_with_lines(f"Time taken to convert shp into geojson: {time_end_shp_process - time_start_conversion}")


            print_with_lines(f"Time taken to process the whole file: {time_end_shp_process - time_start_shp_process}")


            print_with_lines("Saving to database")
            time_start_save_to_database = time.time()
            geojson_data = Files(
                user_id = user_id,
                name = db_filename,
                geojson = geojson_str,
                )
            geojson_data.save()
            time_end_save_to_database = time.time()
            print_with_lines(f"Time taken to save to database: {time_end_save_to_database - time_start_save_to_database}")      

            response.set_cookie('user_id', user_id, max_age= 3 * 24 * 60 * 60)

            return response
        else:
    
            return render(request, self.template_name, {'form': form})
        

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataCollect</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@v7.3.0/ol.css">
    <script src="https://cdn.jsdelivr.net/npm/ol@v7.3.0/dist/ol.js"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/shp-write@latest/shpwrite.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.js" integrity="sha512-3FKAKNDHbfUwAgW45wNAvfgJDDdNoTi5PZWU7ak3Xm0X8u0LbDBWZEyPklRebTZ8r+p0M2KIJWDYZQjDPyYQEA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- stylesheet staticfiles project -->
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}" />

</head>
  <body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
      <a class="navbar-brand" href="#">
        <img src="{% static 'Untitled.png' %}" width="2%" height="6%" id="nav-image1">
        <img src="{% static 'Untitled.png' %}" width="3%" height="6%" id="nav-image2">
        <img src="{% static 'Untitled.png' %}" width="4%" height="8%" id="nav-image3">
        <img src="{% static 'Untitled.png' %}" width="5%" height="10%" id="nav-image4">
      </a>

    </nav>
    <!--Analysis Toolbar-->

      <div class="btn-toolbar collapse" id="collapseToolbar" role="toolbar" aria-label="Toolbar with button groups">

        <div class="btn-group me-2" role="group" aria-label="First group">
          <button type="button" class="btn btn-secondary btn-toolbar-custom">Clip</button>
          <button type="button" class="btn btn-secondary btn-toolbar-custom">Buffer</button>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-secondary btn-toolbar-custom dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Measure
            </button>
            <ul class="dropdown-menu" id="measure-dropdown" disabled>
              <li><a class="dropdown-item disabled" href="#" id="length">Length</a></li>
              <li><a class="dropdown-item disabled" href="#" id="area">Area</a></li>
            </ul>
          </div>
        </div>
        
      </div>

  

    <!--Map-->
    <div id="map" class="map">
        <a class="btn-button btn-overlay btn-collapse" data-bs-toggle="collapse" href="#collapseToolbar" role="button" aria-expanded="false" aria-controls="collapseToolbar">
          Toggle Toolbar
        </a>
    </div>

    <!--Popup-->
    <div id="popup" class="ol-popup">
      <a href="#" id="popup-closer" class="ol-popup-closer"></a>
      <div id="popup-content"></div>
    </div>



    <!--Attribute Table-->
    <div id="feat-attr">
      <ul>
        <li>Once you import your dataset, you will be able to edit your dataset's field attributes by clicking on a feature on the map and export the edited dataset.</li>
        <li>Before going for data collection in the field, you should add the fields that you want collect the data for in your dataset.</li>
      </ul>
    </div>

    <!--Tracking-->
    <div class="container text-center">
      <div class="row">
        <div class="col" id="import">
          <button type="button" class="btn btn-secondary" id="import-btn">Import shapefiles</button>
        </div>
        <div class="col">
        <!--Layer Dropdown-->
          <div class="dropdown" id="layer-dropdown-div">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Download Layer
            </button>
              <ul id="layer-dropdown" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li class="default-option">Load layers first</li>
              </ul>
          </div>
        </div>
        <div class="col">
          <label for="track">
            <input id="track" type="checkbox">
            Track Your Position
          </label>
          <button type="button" class="btn btn-secondary" id="recenter">Recenter</button>
        </div>
      </div>
      <div class="row">
        <div class="col">
          Position Accuracy <code id="accuracy"></code>
        </div>
        <div class="col">
          Altitude <code id="altitude"></code>
        </div>
        <div class="col">
          Altitude Accuracy <code id="altitudeAccuracy"></code>
        </div>
        <div class="col">
          Heading <code id="heading"></code>
        </div>
        <div class="col">
          Speed <code id="speed"></code>
        </div>
      </div>
    </div>

    <!--Modal-->
    <div class="modal fade" id="response-modal" tabindex="-1" aria-labelledby="response-modal-label" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="response-modal-label">Progress</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p id="response-message"></p>
            <div class="progress">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
            </div>
          </div>
        </div>
      </div>
    </div>


    {% block content %}
    {% endblock %}

  

    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
        </a>
        <span class="mb-3 mb-md-0 text-muted">&copy; 2023 Proghead</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="https://github.com/Proghead231" target="_blank"><img src="https://github.githubassets.com/favicons/favicon.svg"></a></li>
      </ul>
    </footer>




    <script>
        document.getElementById("import-btn").addEventListener("click", function() {
            window.location.href = "{% url 'main:save-shapefiles' %}";
        });
    </script>

      <!-- script staticfiles project -->
    <script src="https://cdn.jsdelivr.net/npm/elm-pep@1.0.6/dist/elm-pep.js"></script>
    <script type="module" src="{% static 'main/js/main.js' %}"></script>
    <script type="module" src="{% static 'main/js/measure.js' %}"></script>


  </body>
</html>

main/templates/main/upload_shapefile.html
{% extends "main/index.html" %}
{% block content %}

<form method="POST" enctype="multipart/form-data" id="form" action="{% url 'main:save-shapefiles' %}">
  {% csrf_token %}
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <div class="form-group">
          <label for="file-upload">Select Shapefile along with .dbf,.prj and .shx</label>
          <input id="file-upload" type="file" name="zipfile" multiple accept=".shp,.dbf,.prj,.shx">
          <button id="import-button" type="submit" disabled>Import</button>
          <div id="file-list"></div>
        </div>
      </div>
    </div>
  </div>
      <script>
        const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100 MB
      
        const fileInput = document.getElementById("file-upload");
        const fileListDiv = document.getElementById("file-list");
        const importButton = document.getElementById("import-button");
        
        importButton.disabled = true;
        let files;
        fileInput.addEventListener("change", function(event) {
          files = event.target.files;
          const fileNames = Array.from(files).map(file => file.name);
      
          const fileNamesWithoutExtensions = Array.from(files).map(file => file.name.split('.').slice(0, -1).join('.'));
          const uniqueNames = [...new Set(fileNamesWithoutExtensions)];
      
          if (uniqueNames.length != 1 || files.length > 4){
            alert("Please only select a shapefile and its associated files")
          }
                
          const requiredExtensions = [".shp", ".dbf", ".prj", ".shx"];
          const selectedExtensions = fileNames.map(name => name.substr(name.lastIndexOf(".")));
                
          for (let i = 0; i < requiredExtensions.length; i++) {
            if (!selectedExtensions.includes(requiredExtensions[i])) {
              alert("Please select a " + requiredExtensions[i] + " file.");
              return;
            }
          }
              
          fileListDiv.innerHTML = "";
          let totSize = 0;
          for (let i = 0; i < files.length; i++) {
            console.log("File size before compression", files[i].size, "bytes")
            totSize = totSize + files[i].size;
            if (files[i].size > MAX_FILE_SIZE) {
              alert("Shapefile is too large, it will take a lot of time to send the file to the server.");
              importButton.disabled = false;
              return;
            }
          }
          console.log("Total size: ", totSize, "bytes");
          importButton.disabled = false;
        });
          
        importButton.addEventListener("click", function(event) {
          event.preventDefault();

          var responseModal = new bootstrap.Modal(document.getElementById('response-modal'));
          responseModal.show()
          
          var progressBar = responseModal._element.querySelector('.progress-bar');
          var messageElement = responseModal._element.querySelector('.modal-body p');
          progressBar.style.width='0%';
          messageElement.textContent='';

          function updateProgressBar(percentProgress, message){
            progressBar.style.width= percentProgress
            messageElement.textContent = message
          }

          // Compress selected files into a ZIP file
          const startTime = Date.now()
          updateProgressBar('10%', 'Compressing the files...')
          const zip = new JSZip();
          for (let i = 0; i < files.length; i++) {
            zip.file(files[i].name, files[i]);
          }
          updateProgressBar('20%', 'Compressing the files...')
          
          updateProgressBar('30%', 'Compressing the files...')
          zip.generateAsync({
            type:"blob",
            compression: "DEFLATE",
            compressionOption: {
              level: 9
            }
          })
          .then(function(zipBlob) {
            updateProgressBar('40%', 'Compressing the files...')
            updateProgressBar('40%', 'Preparing to send the compressed file to the server...')
            if (zipBlob.size > 20000000){
              updateProgressBar('40%', 'Your compressed file is larger than 20 mb so it might take some time to send it to the server...')
            }
            // Set the ZIP file as the form data
            updateProgressBar('50%', 'Preparing to send the compressed file to the server...')
            console.log("Zip file being sent: ", zipBlob);
            console.log("Compressed file size: ", zipBlob.size, "bytes");
            const formData = new FormData();
            const zipFileName = files.length > 0 ? files[0].name.replace(/\.[^/.]+$/, "") + ".zip" : "files.zip";
            formData.append("zipfile", zipBlob, zipFileName);
            formData.set("csrfmiddlewaretoken", "{{ csrf_token }}");
            updateProgressBar('60%', 'Preparing to send the compressed file ' + zipFileName + ' to the server...')
            console.log("Form being sent: ", formData)
            console.log("Files compressed and ready to be sent")
            
            // Send the POST request with the ZIP file data
            if (zipBlob.size > 20000000){
              updateProgressBar('90%', 'Making a post request with ' + zipFileName+ ' Your compressed file is larger than 20 mb so it might take some time to send it to the server...')
            } else  {
              updateProgressBar('90%', 'Making a post request with ' + zipFileName)
            }
            
            fetch("{% url 'main:save-shapefiles' %}", {
              method: 'POST',
              body: formData,
              headers: {
                'X-CSRFToken': "{{ csrf_token }}"
              }
            })
            .then(function(response) {
              if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
                updateProgressBar('90%', `HTTP error! status: ${response.status}` )
              }
              return response.json();
              updateProgressBar('90%', 'Made a post request wth ' + zipFileName + ', waiting for a response from the server...')
              console.log("Post request sent");
            })
            .then(function(data){
              const endTime = Date.now();
              updateProgressBar('100%', data.success_msg + " Time taken: " + (((endTime - startTime)/1000)/60).toFixed(3)+ " minute/s");
              console.log("Success message: " + data.success_msg);

            })
            .catch(function(err) {
              alert(err);
            });
          })
          .catch(function(err) {
            alert(err);
          });
        });
        
      </script>
</form>
{% endblock content %}